### ISSUE TITLE
Error when training without any pretrained model

### ISSUE THREAD

**Issue by hanur13** [XuJiacong/PIDNet#21]
I tried training a Camvid dataset with Imagenet and Cityscapes' pretrained model but the best_mIoU on both are over 0.9 (I don't know it was a good result or overconfidence??)

So I want to know the mIoU on Camvid dataset without any pretrained model

I've changed the config file in MODEL.PRETRAINED into false. But I got error message below:

> Traceback (most recent call last):
  File "tools/train.py", line 218, in <module>
    main()
  File "tools/train.py", line 50, in main
    args = parse_args()
  File "tools/train.py", line 44, in parse_args
    update_config(config, args)
  File "/home/ubuntu/workdir/nur/PIDNet/tools/../configs/default.py", line 94, in update_config
    cfg.merge_from_file(args.cfg)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/yacs/config.py", line 474, in _merge_a_into_b
    v = _check_and_coerce_cfg_value_type(v, b[k], k, full_key)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/yacs/config.py", line 534, in _check_and_coerce_cfg_value_type
    raise ValueError(
ValueError: Type mismatch (<class 'str'> vs. <class 'bool'>) with values (pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar vs. False) for config key: MODEL.PRETRAINED

Where should I troubleshoot the code(s) to train a Camvid dataset without any pretrained model?

Thanks

**Comment by XuJiacong** [comment]
I think that is overconfidence. Since the camvid website is broken down, you could check the guidance I provided for preparation of camvid dataset. Please delete all the codes that cause error.
