### ISSUE TITLE
Training error on transfer learning with only one category

### ISSUE THREAD

**Issue by yunxi1** [XuJiacong/PIDNet#44]
Hi, thank you for your excellent work,I used the model you trained in cityscapes as a pre training model to learn a new task with only one category. The label format of the data is a binary grayscale image, where the background pixel value is 0, and the foreground pixel value is 255. I rewrote cityscapes.py to adapt to the new dataset. The main changes are as follows：
```
# ignore_label=255
self.label_mapping = {0: ignore_label,
                              255: 0}   # cloud: 0, bg:255

 self.class_weights = None
```
And reset the. yaml file, NUM_CLASSES=1，
**But the output loss is nan, I don't know why. Do the authors have any suggestions?**

**log:**
Epoch: [0/484] Iter:[0/40], Time: 1.96, lr: [0.01], Loss: nan, Acc:0.516756, Semantic loss: nan, BCE loss: 3.564931, SB loss: nan
Traceback (most recent call last):
  File "tools/train.py", line 218, in <module>
    main()
  File "tools/train.py", line 182, in main
    trainloader, optimizer, model, writer_dict)
  File "/home/shen/network/cloud_detection/PIDNet-main/tools/../utils/function.py", line 43, in train
    losses, _, acc, loss_list = model(images, labels, bd_gts)
  File "/home/shen/software/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shen/software/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/shen/software/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shen/network/cloud_detection/PIDNet-main/tools/../utils/utils.py", line 54, in forward
    loss_sb = self.sem_loss(outputs[-2], bd_label)
  File "/home/shen/software/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shen/network/cloud_detection/PIDNet-main/tools/../utils/criterion.py", line 96, in forward
    return sb_weights * self._ohem_forward(score[0], target)
  File "/home/shen/network/cloud_detection/PIDNet-main/tools/../utils/criterion.py", line 73, in _ohem_forward
    min_value = pred[min(self.min_kept, pred.numel() - 1)]
IndexError: index -1 is out of bounds for dimension 0 with size 0

**Comment by 17648145240** [comment]
@yunxi1 Can you reproduce the author's original code? If it reproduces, can you share the compressed package with me, thank you very much! My email: 202131903057@stu.hebut.edu.cn

**Comment by yunxi1** [comment]
@17648145240 As shown in the question, there is no solution. Perhaps you can try it yourself

**Comment by yunxi1** [comment]
The problem has been solved. There are two aspects: 
1. For binary classification, we need to set the total category to 2 (including foreground and background). Used to cope with NANs caused by nn.CrossEntropyLoss.

# NUM_CLASSES: 2
# IGNORE_ LABEL: -1
self.label_ mapping = {255：1} # cloud: 1, bg:0

2. For another error that may result, refer to https://github.com/XuJiacong/PIDNet/issues/14#issuecomment-1305105993

3. self.class_weights may also need to be adjusted based on the proportion of positive and negative samples

**Comment by Wooho-Moon** [comment]
Hi, I'm also trying to train with only one classes. but I don't fully understand your comment. could you explain more detailly?

**Comment by Wooho-Moon** [comment]
i set self.label_mapping and self.class_weights like the following

self.label_mapping = { 255:1 }
self.class_weights = torch.FloatTensor([0.8373, 0.918]).cuda()

my input label fg is also 255 and bg is 0 but it output errors.

the error ls CUDA error: device-sied assert triggered . It  usually resulted in unmatched num_classes.
I set NUM_CLASSES : 2. but I don't know what to do anymore .. could you do me a favor?
