### ISSUE TITLE
为啥有的图片可以运行，有的图片会报错呢

### ISSUE THREAD

**Issue by tcoln** [XuJiacong/PIDNet#88]
python tools/custom.py --a 'pidnet-s' --p './pretrained_models/cityscapes/PIDNet_S_Cityscapes_test.pt' --t '.png'
报错信息：
Traceback (most recent call last):
  File "tools/custom.py", line 94, in <module>
    pred = model(img)
  File "/mnt/data/glt/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/glt/safep/ponding/PIDNet/tools/../models/pidnet.py", line 149, in forward
    x_d = x_d + F.interpolate(
RuntimeError: The size of tensor a (209) must match the size of tensor b (208) at non-singleton dimension 2
报错图片：链接：https://pan.baidu.com/s/1tloW25TLcR69xglzwcIPtQ  提取码：1234

**Comment by sym330** [comment]
same error
